# Generated by Django 6.0.3 on 2026-03-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('tuition', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
